"""Initial schema

Revision ID: b0a11b8e62b2
Revises: 
Create Date: 2026-03-30 13:38:05.722175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.db_types  # noqa: F401  # GUID type used inside upgrade()


# revision identifiers, used by Alembic.
revision: str = 'b0a11b8e62b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', app.core.db_types.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=50), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('skills', app.core.db_types.StringArray(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('subscription_tier', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('cost_per_1k_input', sa.Float(), nullable=False),
    sa.Column('cost_per_1k_output', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_user_id'), ['user_id'], unique=False)

    op.create_table('custom_pools',
    sa.Column('id', app.core.db_types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.core.db_types.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('agents_config', app.core.db_types.JSONB(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_pools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_pools_user_id'), ['user_id'], unique=False)

    op.create_table('goals',
    sa.Column('id', app.core.db_types.GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('distribution_mode', sa.String(length=20), nullable=False),
    sa.Column('economy_mode', sa.Boolean(), nullable=False),
    sa.Column('max_exchanges', sa.Integer(), nullable=True),
    sa.Column('output_folder', sa.String(length=1000), nullable=True),
    sa.Column('runtime_mode', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_user_id'), ['user_id'], unique=False)

    op.create_table('organizations',
    sa.Column('id', app.core.db_types.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('owner_id', app.core.db_types.GUID(length=36), nullable=False),
    sa.Column('plan', sa.String(length=30), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', app.core.db_types.GUID(length=36), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(length=36), nullable=True),
    sa.Column('org_role', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('tasks_used_this_month', sa.Integer(), nullable=False),
    sa.Column('tasks_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('trial_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_plan', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', app.core.db_types.GUID(length=36), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.core.db_types.GUID(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memories',
    sa.Column('id', app.core.db_types.GUID(length=36), nullable=False),
    sa.Column('goal_id', app.core.db_types.GUID(length=36), nullable=False),
    sa.Column('global_context', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_decisions', app.core.db_types.JSONB(), nullable=True),
    sa.Column('task_results', app.core.db_types.JSONB(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id')
    )
    op.create_table('messages',
    sa.Column('id', app.core.db_types.GUID(length=36), nullable=False),
    sa.Column('goal_id', app.core.db_types.GUID(length=36), nullable=False),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('sender_agent_id', app.core.db_types.GUID(length=36), nullable=True),
    sa.Column('sender_name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_templates',
    sa.Column('id', app.core.db_types.GUID(length=36), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(length=36), nullable=False),
    sa.Column('created_by', app.core.db_types.GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('distribution_mode', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', app.core.db_types.GUID(length=36), nullable=False),
    sa.Column('goal_id', app.core.db_types.GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('assigned_agent_id', app.core.db_types.GUID(length=36), nullable=True),
    sa.Column('depends_on', app.core.db_types.StringArray(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('result_files', app.core.db_types.StringArray(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('task_templates')
    op.drop_table('messages')
    op.drop_table('memories')
    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_user_id'))

    op.drop_table('goals')
    with op.batch_alter_table('custom_pools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_pools_user_id'))

    op.drop_table('custom_pools')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_user_id'))

    op.drop_table('agents')
    # ### end Alembic commands ###
